#ifndef PYTHIAGEANT_ROOTSCHEMA_HH
#define PYTHIAGEANT_ROOTSCHEMA_HH

#include <array>
#include <string_view>

namespace pg::root_schema {

inline constexpr int kWorkerSeedVersion = 2;
inline constexpr int kPrimaryEventStableVersion = 3;
inline constexpr int kTransportEventStableVersion = 4;
inline constexpr int kCurrentVersion = kTransportEventStableVersion;

constexpr bool IsSupportedVersion(const int version) {
  return version == kWorkerSeedVersion ||
         version == kPrimaryEventStableVersion ||
         version == kTransportEventStableVersion;
}

constexpr bool HasEventTransportSeed(const int version) {
  return version == kTransportEventStableVersion;
}

inline constexpr std::array<std::string_view, 17> kEventBranchesV2V3 = {
    "run",
    "event",
    "bcid",
    "mu_configured",
    "n_interactions_requested",
    "n_interactions_generated",
    "generation_failures",
    "generator_particles",
    "transported_particles",
    "unknown_pdg_particles",
    "total_edep_mev",
    "rejected_not_final",
    "rejected_neutrino_disabled",
    "rejected_invisible_non_neutrino",
    "rejected_outside_eta_acceptance",
    "unlineaged_steps",
    "segmentation_failures",
};

inline constexpr std::array<std::string_view, 18> kEventBranchesV4 = {
    "run",
    "event",
    "bcid",
    "mu_configured",
    "n_interactions_requested",
    "n_interactions_generated",
    "generation_failures",
    "generator_particles",
    "transported_particles",
    "unknown_pdg_particles",
    "total_edep_mev",
    "rejected_not_final",
    "rejected_neutrino_disabled",
    "rejected_invisible_non_neutrino",
    "rejected_outside_eta_acceptance",
    "unlineaged_steps",
    "segmentation_failures",
    "geant4_transport_seed",
};

inline constexpr std::array<std::string_view, 19> kHitBranches = {
    "run",
    "event",
    "bcid",
    "subevent",
    "cell_id",
    "subdetector",
    "sampling",
    "side",
    "eta_index",
    "phi_index",
    "eta_center",
    "phi_center",
    "edep_mev",
    "time_mean_ns",
    "time_first_ns",
    "leading_pdg",
    "leading_track_id",
    "leading_parent_id",
    "steps",
};

inline constexpr std::array<std::string_view, 26> kGeneratorBranches = {
    "run",
    "event",
    "bcid",
    "subevent",
    "index",
    "pdg",
    "status",
    "mother1",
    "mother2",
    "daughter1",
    "daughter2",
    "is_final",
    "is_visible",
    "px_gev",
    "py_gev",
    "pz_gev",
    "energy_gev",
    "mass_gev",
    "eta",
    "phi",
    "x_prod_mm",
    "y_prod_mm",
    "z_prod_mm",
    "t_prod_mm_over_c",
    "accepted_for_transport",
    "rejection_code",
};

inline constexpr std::array<std::string_view, 39> kMetadataBranchesV2 = {
    "schema_version",
    "project_version",
    "git_commit",
    "git_describe",
    "root_version",
    "geant4_version",
    "pythia_version",
    "run",
    "events",
    "first_bcid",
    "threads",
    "seed_base",
    "geant4_master_seed",
    "pythia_seed_base",
    "pythia_worker_seed_stride",
    "pythia_seed_max",
    "interaction_mode",
    "mean_interactions",
    "fixed_interactions",
    "pythia_config",
    "physics_list",
    "production_cut_mm",
    "beam_sigma_x_mm",
    "beam_sigma_y_mm",
    "beam_sigma_z_mm",
    "beam_sigma_t_ns",
    "max_abs_eta",
    "transport_neutrinos",
    "generator_audit",
    "check_overlaps",
    "print_every",
    "config_file",
    "output_file",
    "normalized_config",
    "generator_mode",
    "single_particle_pdg",
    "single_particle_kinetic_energy_gev",
    "single_particle_eta",
    "single_particle_phi",
};

inline constexpr std::array<std::string_view, 42> kMetadataBranchesV3 = {
    "schema_version",
    "project_version",
    "git_commit",
    "git_describe",
    "root_version",
    "geant4_version",
    "pythia_version",
    "run",
    "events",
    "first_bcid",
    "threads",
    "seed_base",
    "geant4_master_seed",
    "seed_policy",
    "seed_identity",
    "seed_mixer",
    "pythia_initialization_seed",
    "pythia_seed_max",
    "pythia_reseed_scope",
    "interaction_mode",
    "mean_interactions",
    "fixed_interactions",
    "pythia_config",
    "physics_list",
    "production_cut_mm",
    "beam_sigma_x_mm",
    "beam_sigma_y_mm",
    "beam_sigma_z_mm",
    "beam_sigma_t_ns",
    "max_abs_eta",
    "transport_neutrinos",
    "generator_audit",
    "check_overlaps",
    "print_every",
    "config_file",
    "output_file",
    "normalized_config",
    "generator_mode",
    "single_particle_pdg",
    "single_particle_kinetic_energy_gev",
    "single_particle_eta",
    "single_particle_phi",
};

inline constexpr std::array<std::string_view, 48> kMetadataBranchesV4 = {
    "schema_version",
    "project_version",
    "git_commit",
    "git_describe",
    "root_version",
    "geant4_version",
    "pythia_version",
    "run",
    "events",
    "first_bcid",
    "threads",
    "seed_base",
    "geant4_master_seed",
    "seed_policy",
    "seed_identity",
    "seed_mixer",
    "pythia_initialization_seed",
    "pythia_seed_max",
    "pythia_reseed_scope",
    "interaction_mode",
    "mean_interactions",
    "fixed_interactions",
    "pythia_config",
    "physics_list",
    "production_cut_mm",
    "beam_sigma_x_mm",
    "beam_sigma_y_mm",
    "beam_sigma_z_mm",
    "beam_sigma_t_ns",
    "max_abs_eta",
    "transport_neutrinos",
    "generator_audit",
    "check_overlaps",
    "print_every",
    "config_file",
    "output_file",
    "normalized_config",
    "generator_mode",
    "single_particle_pdg",
    "single_particle_kinetic_energy_gev",
    "single_particle_eta",
    "single_particle_phi",
    "geant4_transport_seed_policy",
    "geant4_transport_seed_identity",
    "geant4_transport_seed_mixer",
    "geant4_transport_seed_stream",
    "geant4_transport_seed_max",
    "geant4_transport_reseed_scope",
};

}  // namespace pg::root_schema

#endif
